# Site settings
title: affinity tech
email: info@affinity-tech.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://www.affinity-tech.com"
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
include: ['blog']
highlighter: rouge
