name: affinity tech
markdown: redcarpet
highlighter: pygments
url: "http://www.affinity-tech.com"
description: "yo yo yo"
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]
navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects.html
 - title: Contact
   url: /contact.html
